global:
  scrape_interval: 30s
  scrape_timeout: 10s
rule_files:
  - alert.yml
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: grafana
    static_configs:
      - targets:
          - 'grafana:3000'
  - job_name: postgres
    static_configs:
      - targets:
          - 'postgres-exporter:9187'
  - job_name: sql
    static_configs:
      - targets:
          - 'sql-exporter:9399'
  - job_name: cadvisor
    static_configs:
      - targets:
          - '10.0.0.48:9080'
          - '10.0.0.220:9080'
          - '10.0.0.134:9080'
          - '10.0.0.150:9080'
          - 'netcup0.nue.pico.sh:9080'
  - job_name: node_exporter
    static_configs:
      - targets:
          - '10.0.0.48:9100'
          - '10.0.0.220:9100'
          - '10.0.0.134:9100'
          - '10.0.0.150:9100'
          - 'netcup0.nue.pico.sh:9100'
  - job_name: app-ssh
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_ssh/metrics
    static_configs:
      - targets:
          - pico.sh
          - prose.sh
          - pastes.sh
          - pgs.sh
          - nue.pgs.sh
          - feeds.pico.sh
          - pipe.pico.sh
  - job_name: app-web
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_web/metrics
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - pgs.sh
          - nue.pgs.sh
          - feeds.pico.sh
          - pipe.pico.sh
          - auth.pico.sh
  - job_name: tuns
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_sish/metrics
    static_configs:
      - targets:
          - tuns.sh
          - nue.tuns.sh
  - job_name: soju
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_app/metrics
    static_configs:
      - targets:
          - irc.pico.sh
  - job_name: caddy
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_caddy/metrics
    static_configs:
      - targets:
          - pico.sh
          - prose.sh
          - pastes.sh
          - pgs.sh
          - nue.pgs.sh
          - feeds.pico.sh
          - monitoring.pico.sh
          - minio.pico.sh
          - auth.pico.sh
          - pipe.pico.sh
  - job_name: minio
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - minio.pico.sh
  - job_name: imgprpxy
    tls_config:
      insecure_skip_verify: true
    scheme: https
    static_configs:
      - targets:
          - imgproxy.pico.sh
  - job_name: blackbox_exporter_ping
    metrics_path: /probe
    params:
      module:
        - icmp_check
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - pgs.sh
          - nue.pgs.sh
          - feeds.pico.sh
          - tuns.sh
          - nue.tuns.sh
          - monitoring.pico.sh
          - minio.pico.sh
          - chat.pico.sh
          - auth.pico.sh
          - imgproxy.pico.sh
          - pipe.pico.sh
  - job_name: blackbox_exporter_ping_ip6
    metrics_path: /probe
    params:
      module:
        - icmp_check_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - pgs.sh
          - nue.pgs.sh
          - feeds.pico.sh
          - tuns.sh
          - nue.tuns.sh
          - monitoring.pico.sh
          - minio.pico.sh
          - chat.pico.sh
          - auth.pico.sh
          - imgproxy.pico.sh
          - pipe.pico.sh
  - job_name: blackbox_exporter_ssh
    metrics_path: /probe
    params:
      module:
        - ssh_banner
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'prose.sh:22'
          - 'pastes.sh:22'
          - 'pgs.sh:22'
          - 'nue.pgs.sh:22'
          - 'feeds.pico.sh:22'
          - 'pipe.pico.sh:22'
          - 'tuns.sh:22'
          - 'nue.tuns.sh:22'
          - 'prose.sh:650'
          - 'pastes.sh:650'
          - 'pgs.sh:650'
          - 'nue.pgs.sh:650'
          - 'feeds.pico.sh:650'
          - 'monitoring.pico.sh:650'
          - 'minio.pico.sh:650'
          - 'chat.pico.sh:650'
          - 'auth.pico.sh:650'
          - 'pipe.pico.sh:650'
  - job_name: blackbox_exporter_ssh_ip6
    metrics_path: /probe
    params:
      module:
        - ssh_banner_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'prose.sh:22'
          - 'pastes.sh:22'
          - 'pgs.sh:22'
          - 'nue.pgs.sh:22'
          - 'feeds.pico.sh:22'
          - 'pipe.pico.sh:22'
          - 'tuns.sh:22'
          - 'nue.tuns.sh:22'
          - 'prose.sh:650'
          - 'pastes.sh:650'
          - 'pgs.sh:650'
          - 'nue.pgs.sh:650'
          - 'feeds.pico.sh:650'
          - 'monitoring.pico.sh:650'
          - 'minio.pico.sh:650'
          - 'chat.pico.sh:650'
          - 'auth.pico.sh:650'
          - 'pipe.pico.sh:650'
  - job_name: blackbox_exporter_https_2xx
    metrics_path: /probe
    params:
      module:
        - https_get_2xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'https://prose.sh'
          - 'https://pastes.sh'
          - 'https://pgs.sh'
          - 'https://feeds.pico.sh'
          - 'https://monitoring.pico.sh'
          - 'https://chat.pico.sh'
          - 'https://pipe.pico.sh'
  - job_name: blackbox_exporter_https_2xx_ip6
    metrics_path: /probe
    params:
      module:
        - https_get_2xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'https://prose.sh'
          - 'https://pastes.sh'
          - 'https://pgs.sh'
          - 'https://feeds.pico.sh'
          - 'https://monitoring.pico.sh'
          - 'https://chat.pico.sh'
          - 'https://pipe.pico.sh'
  - job_name: blackbox_exporter_https_3xx
    metrics_path: /probe
    params:
      module:
        - https_get_3xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'https://tuns.sh'
          - 'https://nue.tuns.sh'
  - job_name: blackbox_exporter_https_3xx_ip6
    metrics_path: /probe
    params:
      module:
        - https_get_3xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'https://tuns.sh'
          - 'https://nue.tuns.sh'
  - job_name: blackbox_exporter_https_4xx
    metrics_path: /probe
    params:
      module:
        - https_get_4xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'https://minio.pico.sh'
          - 'https://auth.pico.sh'
          - 'https://nue.pgs.sh'
  - job_name: blackbox_exporter_https_4xx_ip6
    metrics_path: /probe
    params:
      module:
        - https_get_4xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'https://minio.pico.sh'
          - 'https://auth.pico.sh'
          - 'https://nue.pgs.sh'
  - job_name: blackbox_exporter_http_3xx
    metrics_path: /probe
    params:
      module:
        - http_get_3xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'http://prose.sh'
          - 'http://pastes.sh'
          - 'http://pgs.sh'
          - 'http://nue.pgs.sh'
          - 'http://feeds.pico.sh'
          - 'http://tuns.sh'
          - 'http://nue.tuns.sh'
          - 'http://monitoring.pico.sh'
          - 'http://minio.pico.sh'
          - 'http://chat.pico.sh'
          - 'http://auth.pico.sh'
          - 'http://imgproxy.pico.sh'
          - 'http://pipe.pico.sh'
  - job_name: blackbox_exporter_http_3xx_ip6
    metrics_path: /probe
    params:
      module:
        - http_get_3xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'http://prose.sh'
          - 'http://pastes.sh'
          - 'http://pgs.sh'
          - 'http://nue.pgs.sh'
          - 'http://feeds.pico.sh'
          - 'http://tuns.sh'
          - 'http://nue.tuns.sh'
          - 'http://monitoring.pico.sh'
          - 'http://minio.pico.sh'
          - 'http://chat.pico.sh'
          - 'http://auth.pico.sh'
          - 'http://imgproxy.pico.sh'
          - 'http://pipe.pico.sh'
  - job_name: blackbox_exporter_tls
    metrics_path: /probe
    params:
      module:
        - tcps_connect
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'irc.pico.sh:6697'
  - job_name: blackbox_exporter_tls_ip6
    metrics_path: /probe
    params:
      module:
        - tcps_connect_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
    static_configs:
      - targets:
          - 'irc.pico.sh:6697'
