global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000
  - job_name: cadvisor
    static_configs:
      - targets:
          - 10.0.0.48:9080 # oracle0
          - 10.0.0.211:9080 # oracle1
          - 10.0.0.101:9080 # oracle2
          - 10.0.0.150:9080 # oracle3
  - job_name: node_exporter
    static_configs:
      - targets:
          - 10.0.0.48:9100 # oracle0
          - 10.0.0.211:9100 # oracle1
          - 10.0.0.101:9100 # oracle2
          - 10.0.0.150:9100 # oracle3
  - job_name: wish
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_app/metrics
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - lists.sh
          - imgs.sh
          - pgs.sh
          - feeds.sh
  - job_name: caddy
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /_caddy/metrics
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - lists.sh
          - imgs.sh
          - pgs.sh
          - feeds.sh
          - monitoring.pico.sh
          - minio.pico.sh
          - auth.pico.sh
  - job_name: minio
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - minio.pico.sh
  - job_name: imgprpxy
    tls_config:
      insecure_skip_verify: true
    scheme: https
    static_configs:
      - targets:
          - imgproxy.pico.sh
  - job_name: blackbox_exporter_ping
    metrics_path: "/probe"
    params:
      module:
        - icmp_check
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - lists.sh
          - imgs.sh
          - pgs.sh
          - feeds.sh
          - monitoring.pico.sh
          - minio.pico.sh
          - chat.pico.sh
          - auth.pico.sh
          - imgproxy.pico.sh
  - job_name: blackbox_exporter_ping_ip6
    metrics_path: "/probe"
    params:
      module:
        - icmp_check_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - prose.sh
          - pastes.sh
          - lists.sh
          - imgs.sh
          - pgs.sh
          - feeds.sh
          - monitoring.pico.sh
          - minio.pico.sh
          - chat.pico.sh
          - auth.pico.sh
          - imgproxy.pico.sh
  - job_name: blackbox_exporter_ssh
    metrics_path: "/probe"
    params:
      module:
        - ssh_banner
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - prose.sh:22
          - pastes.sh:22
          - lists.sh:22
          - imgs.sh:22
          - pgs.sh:22
          - feeds.sh:22
          - prose.sh:650
          - pastes.sh:650
          - lists.sh:650
          - imgs.sh:650
          - pgs.sh:650
          - feeds.sh:650
          - monitoring.pico.sh:650
          - minio.pico.sh:650
          - chat.pico.sh:650
          - auth.pico.sh:650
  - job_name: blackbox_exporter_ssh_ip6
    metrics_path: "/probe"
    params:
      module:
        - ssh_banner_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - prose.sh:22
          - pastes.sh:22
          - lists.sh:22
          - imgs.sh:22
          - pgs.sh:22
          - feeds.sh:22
          - prose.sh:650
          - pastes.sh:650
          - lists.sh:650
          - imgs.sh:650
          - pgs.sh:650
          - feeds.sh:650
          - monitoring.pico.sh:650
          - minio.pico.sh:650
          - chat.pico.sh:650
          - auth.pico.sh:650
  - job_name: blackbox_exporter_https_2xx
    metrics_path: "/probe"
    params:
      module:
        - https_get_2xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - https://prose.sh
          - https://pastes.sh
          - https://lists.sh
          - https://imgs.sh
          - https://pgs.sh
          - https://feeds.sh
          - https://monitoring.pico.sh
          - https://chat.pico.sh
  - job_name: blackbox_exporter_https_2xx_ip6
    metrics_path: "/probe"
    params:
      module:
        - https_get_2xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - https://prose.sh
          - https://pastes.sh
          - https://lists.sh
          - https://imgs.sh
          - https://pgs.sh
          - https://feeds.sh
          - https://monitoring.pico.sh
          - https://chat.pico.sh
  - job_name: blackbox_exporter_https_4xx
    metrics_path: "/probe"
    params:
      module:
        - https_get_4xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - https://minio.pico.sh
          - https://auth.pico.sh
  - job_name: blackbox_exporter_https_4xx_ip6
    metrics_path: "/probe"
    params:
      module:
        - https_get_4xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - https://minio.pico.sh
          - https://auth.pico.sh
  - job_name: blackbox_exporter_http_3xx
    metrics_path: "/probe"
    params:
      module:
        - http_get_3xx
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - http://prose.sh
          - http://pastes.sh
          - http://lists.sh
          - http://imgs.sh
          - http://pgs.sh
          - http://feeds.sh
          - http://monitoring.pico.sh
          - http://minio.pico.sh
          - http://chat.pico.sh
          - http://auth.pico.sh
          - http://imgproxy.pico.sh
  - job_name: blackbox_exporter_http_3xx_ip6
    metrics_path: "/probe"
    params:
      module:
        - http_get_3xx_ip6
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - http://prose.sh
          - http://pastes.sh
          - http://lists.sh
          - http://imgs.sh
          - http://pgs.sh
          - http://feeds.sh
          - http://monitoring.pico.sh
          - http://minio.pico.sh
          - http://chat.pico.sh
          - http://auth.pico.sh
          - http://imgproxy.pico.sh
