version: '3.8'

services:
  caddy:
    env_file:
      - .env.prod
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
  prometheus:
    env_file:
      - .env.prod
    volumes:
      - ./prometheus/data:/prometheus
  grafana:
    env_file:
      - .env.prod
    volumes:
      - ./grafana/data:/var/lib/grafana
  blackbox_exporter:
    networks:
      - default
      - ip6net
    env_file:
      - .env.prod

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:dead:beef::/48