version: '3.8'

services:
  caddy:
    image: ghcr.io/picosh/pico/caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: always
    profiles:
      - caddy
      - all
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --web.external-url https://prometheus.${APP_DOMAIN:-dev.pico.sh} --storage.tsdb.retention.time 90d
    restart: always
    profiles:
      - monitoring
      - all
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/config:/etc/grafana
    restart: always
    profiles:
      - monitoring
      - all
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox-exporter/config:/etc/blackbox-exporter
    command: --config.file=/etc/blackbox-exporter/blackbox.yml
    restart: always
    profiles:
      - monitoring
      - all
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: ${DATABASE_URL:-postgresql://localhost:5432/postgres?sslmode=disable}
    command: |
      --collector.long_running_transactions
      --collector.process_idle
      --collector.stat_activity_autovacuum
      --collector.stat_wal_receiver
      --collector.statio_user_indexes
    restart: always
    profiles:
      - monitoring
      - all
  sql-exporter:
    image: burningalchemist/sql_exporter:latest
    volumes:
      - ./sql-exporter/config:/config
    environment:
      SQLEXPORTER_TARGET_DSN: ${DATABASE_URL:-postgresql://localhost:5432/postgres?sslmode=disable}
    command: |
      -config.file=/config/sql.yml
    restart: always
    profiles:
      - monitoring
      - all
