version: '3.8'

services:
  caddy:
    env_file:
      - .env.prod
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
  prometheus:
    dns: 1.1.1.1
    networks:
      - default
      - caddy
    env_file:
      - .env.prod
    volumes:
      - ./prometheus/data:/prometheus
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1024m"
  grafana:
    networks:
      - default
      - caddy
    env_file:
      - .env.prod
    volumes:
      - ./grafana/data:/var/lib/grafana
  blackbox-exporter:
    dns: 1.1.1.1
    networks:
      - default
      - ip6net
    env_file:
      - .env.prod
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "1024m"

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
        - subnet: fd00:dead:beef:21::/112
  caddy:
    name: pico_prose
    external: true
