{
 "title": "Caddy exporter",
 "description": "Dashboard set for Caddy proxy",
 "tags": [ "caddy" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(caddy_http_requests_total, instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(caddy_http_requests_total{instance=~\"$instance\"}, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP(S) requests total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{instance=~\"$instance\",handler=~\"$handler\"}[5m])*10) by (instance, handler)",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP(S) errors total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_request_errors_total{instance=~\"$instance\",handler=~\"$handler\"}[5m])*10) by (instance, handler)",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Median response size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, instance, handler) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$instance\", handler=~\"$handler\"}[5m])))",
     "legendFormat": "p50 - {{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Median response duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, instance, handler) (rate(caddy_http_response_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[5m])))",
     "legendFormat": "p50 - {{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Request/Response duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$instance\",handler=~\"$handler\"}[5m])) by (instance, handler)",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  }
 ]
}