{
 "title": "Caddy",
 "tags": [
  "http",
  "caddy",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(caddy_http_requests_total, instance)"
    }
   },
   {
    "name": "handler",
    "label": "handler",
    "query": {
     "query": "label_values(caddy_http_requests_total{instance=~\"$instance\"}, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{handler=~\"$handler\", instance=~\"$instance\"}[1m])) by (instance, handler)",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (code, instance, handler)",
     "legendFormat": "{{instance}} - {{handler}} - {{code}}"
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(caddy_http_requests_in_flight{instance=~\"$instance\", handler=~\"$handler\"}[1m])",
     "legendFormat": "{{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Requests by Response Code (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (code, instance, handler)",
     "legendFormat": "{{instance}} - {{handler}} - {{code}}"
    }
   ]
  },
  {
   "title": "Request Duration (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (le, instance, handler))",
     "legendFormat": "p99 - {{instance}} - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (le, instance, handler))",
     "legendFormat": "p95 - {{instance}} - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (le, instance, handler))",
     "legendFormat": "p90 - {{instance}} - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (le, instance, handler))",
     "legendFormat": "p75 - {{instance}} - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[1m])) by (le, instance, handler))",
     "legendFormat": "p50 - {{instance}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Request Duration (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{instance=~\"$instance\", handler=~\"$handler\"}[5m])) by (le, instance, handler)",
     "legendFormat": "{{le}} - {{instance}} - {{handler}}"
    }
   ]
  }
 ]
}