{
 "title": "Soju",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "soju_upstream_connect_errors_total",
     "legendFormat": "Upstream Connection Errors (IRC Servers)"
    },
    { "expr": "soju_worker_panics_total", "legendFormat": "Worker Panics" }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(soju_upstream_connect_errors_total[$__rate_interval])",
     "legendFormat": "Upstream Connection Errors (IRC Servers)"
    },
    {
     "expr": "rate(soju_worker_panics_total[$__rate_interval])",
     "legendFormat": "Worker Panics"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "soju_downstream_in_messages_total",
     "legendFormat": "Downstream In Messages"
    },
    {
     "expr": "soju_downstream_out_messages_total",
     "legendFormat": "Downstream Out Messages"
    },
    {
     "expr": "soju_upstream_in_messages_total",
     "legendFormat": "Upstream In Messages"
    },
    {
     "expr": "soju_upstream_out_messages_total",
     "legendFormat": "Upstream Out Messages"
    }
   ]
  },
  {
   "title": "Message Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(soju_downstream_in_messages_total[$__rate_interval])",
     "legendFormat": "Downstream In Messages"
    },
    {
     "expr": "rate(soju_downstream_out_messages_total[$__rate_interval])",
     "legendFormat": "Downstream Out Messages"
    },
    {
     "expr": "rate(soju_upstream_in_messages_total[$__rate_interval])",
     "legendFormat": "Upstream In Messages"
    },
    {
     "expr": "rate(soju_upstream_out_messages_total[$__rate_interval])",
     "legendFormat": "Upstream Out Messages"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "soju_users_active", "legendFormat": "Active Users" },
    { "expr": "soju_upstreams_active", "legendFormat": "Active Upstreams (IRC Servers)" },
    {
     "expr": "soju_downstreams_active",
     "legendFormat": "Active Downstreams (IRC Clients)"
    }
   ]
  },
  {
   "title": "Connection Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(soju_users_active[$__rate_interval])",
     "legendFormat": "Active Users"
    },
    {
     "expr": "rate(soju_upstreams_active[$__rate_interval])",
     "legendFormat": "Active Upstreams (IRC Servers)"
    },
    {
     "expr": "rate(soju_downstreams_active[$__rate_interval])",
     "legendFormat": "Active Downstreams (IRC Clients)"
    }
   ]
  }
 ]
}