{
 "title": "Tuns",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sish_connections_total", "legendFormat": "Total Connections" }
   ]
  },
  {
   "title": "Tunnels Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(sish_tunnels_active{type=\"alias\"}) or vector(0)",
     "legendFormat": "Alias"
    },
    {
     "expr": "sum(sish_tunnels_active{type=\"tcp\"}) or vector(0)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(sish_tunnels_active{type=\"http\"}) or vector(0)",
     "legendFormat": "HTTP"
    },
    {
     "expr": "sum(sish_tunnels_active{type=\"process\"}) or vector(0)",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "Session Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "time() - sish_connections_time", "legendFormat": "{{user}} - {{connection}}" }
   ]
  },
  {
   "title": "Tunnels",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "label_join(sish_tunnels_active, \"full_tunnel\", \"-\", \"user\", \"tunnel\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"tuns\"}[$__rate_interval])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"tuns\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"tuns\"}",
     "legendFormat": "Fds"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"tuns\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"tuns\"}[$__rate_interval])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total{job=\"tuns\"}[$__rate_interval])",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}