apiVersion: 1

contactPoints:
  - orgId: 1
    name: IRC
    receivers:
      - uid: J9QprMbVz
        type: webhook
        settings:
          url: ${NOTIFY_WEBHOOK}
          httpMethod: POST
          maxAlerts: '0'
  - orgId: 1
    name: Email
    receivers:
      - uid: ec1f06c0-6a32-4698-a861-bac2ea89b7b3
        type: email
        settings:
          addresses: ${NOTIFY_EMAIL}
          singleEmail: false
        disableResolveMessage: false
