apiVersion: 1

groups:
  - orgId: 1
    name: Ping
    folder: Default
    interval: 60s
    rules:
      - id: 4
        uid: ZbqmOnbVz
        orgID: 1
        folderUID: wLZWgnbVz
        ruleGroup: Ping
        title: Ping Status
        condition: C
        data:
        - refId: A
          queryType: ''
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: PBFA97CFB590B2093
          model:
            editorMode: code
            expr: probe_success{job="blackbox_exporter_ping"}
            hide: false
            intervalMs: 1000
            legendFormat: __auto
            maxDataPoints: 43200
            range: true
            refId: A
        - refId: B
          queryType: ''
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: "-100"
          model:
            conditions:
            - evaluator:
                params: []
                type: gt
              operator:
                type: and
              query:
                params:
                - B
              reducer:
                params: []
                type: last
              type: query
            datasource:
              type: __expr__
              uid: "-100"
            expression: A
            hide: false
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: B
            type: reduce
        - refId: C
          queryType: ''
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: "-100"
          model:
            conditions:
            - evaluator:
                params:
                - 1
                type: lt
              operator:
                type: and
              query:
                params:
                - C
              reducer:
                params: []
                type: last
              type: query
            datasource:
              type: __expr__
              uid: "-100"
            expression: B
            hide: false
            intervalMs: 1000
            maxDataPoints: 43200
            refId: C
            type: threshold
        updated: '2023-02-24T20:30:57Z'
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          description: Ping is inaccessible for {{ $labels.instance }}
          summary: Ping is inaccessible for {{ $labels.instance }}
